### ISSUE TITLE
arrch64 embeded

### ISSUE THREAD

**Issue by YSJpw** [ShawnHymel/ei-keyword-spotting#12]
how can i run this on my arrch64 embeded sysyem?

**Comment by ShawnHymel** [comment]
Either use the Edge Impulse Linux runner (https://docs.edgeimpulse.com/docs/edge-impulse-for-linux/edge-impulse-for-linux) or the C++ inference SDK library (https://docs.edgeimpulse.com/docs/deployment/running-your-impulse-locally/deploy-your-model-as-a-c-library).

**Comment by YSJpw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YSJpw** [comment]
Thanks for reply!
About the method of Edge Impulse for Linux,i have got my .eim file,but how can i use it on my system?Here is my error.
![image](https://user-images.githubusercontent.com/100180579/210588969-87cbf45d-8dc1-48f8-ac89-dfacc8469e66.png)

**Comment by YSJpw** [comment]
Sorry, if my system is good enough for real time model, my CPU is ARM Cortex-A55 4 core, 1.8GHz*4.

**Comment by ShawnHymel** [comment]
@YSJpw Please create a post on https://forum.edgeimpulse.com/ for technical support with Edge Impulse. .eim models are outside the scope of this repository (right now).

**Comment by YSJpw** [comment]
Thanks for reply,i have posted my error in our forum.
https://forum.edgeimpulse.com/t/how-can-i-run-it-on-my-aarch64-embeded-system/6176?u=y1165949971
https://forum.edgeimpulse.com/t/how-can-i-run-it-on-my-aarch64-embeded-system/6176?u=y1165949971

世纪
***@***.***



&nbsp;
