### ISSUE TITLE
SensorTile Box from STM32

### ISSUE THREAD

**Issue by shivashankarivr** [ShawnHymel/ei-keyword-spotting#3]
Hi, am planning to do speech recognition on SensorTIle Box. I have followed your TinyMl tutorial for creating models throgh edge impulse. But, I can see you have generated C++ codes in MX for Nucleo l476 board. I just want to know how you have created that .mx project. please explain.

**Comment by ShawnHymel** [comment]
The .mx project is created using the CubeMX tool in the STM32CubeIDE. I recommend watching this video series to see how to use the CubeMX tool: [https://www.youtube.com/watch?v=hyZS2p1tW-g&list=RDCMUCclJCqMDAkyVGsm5oFOTXIQ&index=1](https://www.youtube.com/watch?v=hyZS2p1tW-g&list=RDCMUCclJCqMDAkyVGsm5oFOTXIQ&index=1)
